# configurations
# 详情请参考：https://halo.run/develop/theme.html#settings-yaml
general:
  label: 基本设置
  items:
    home_title:
      name: home_title
      label: 首页展示博客名
      type: text
      placeholder: '用于首页展示名字'
      description: '注意：如填写，会覆盖原有博客名'
    home_description:
      name: home_description
      label: 首页描述
      type: text
      placeholder: '用于首页描述'
    base_color:
      name: base_color
      label: 网站主题色
      type: color
      default: '#2474b5'
      placeholder: '网站主题色'
    home_cover:
      name: home_cover
      label: 首页背景
      type: attachment
    enabled_index_cover_height:
      name: enabled_index_cover_height
      label: 首页开启全屏图片
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    header_logoimg:
      name: header_logoimg
      label: 菜单 Logo
      type: attachment
    header_logo_height:
      name: header_logo_height
      label: 菜单 Logo 高度
      type: text
      placeholder: '比如: 20px'
    post_list_style:
      name: post_list_style
      label: 首页文章风格
      type: radio
      data-type: string
      default: standard
      options:
        - value: standard
          label: 标准
        - value: simple
          label: 简单
        - value: card
          label: 卡片
    card_random_cover:
      name: card_random_cover
      label: 卡片文章风格随机选择封面
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
      description: '即使开启了此选项,也只有文章没有封面的情况下才会生效.请查看教程: https://baozi.fun/archives/random-thumbnail'
    card_random_cover_img_suffix:
      name: card_random_cover_img_suffix
      label: 卡片文章风格随机选择封面后缀
      type: radio
      data-type: string
      default: png
      options:
        - value: png
          label: png
        - value: jpeg
          label: jpeg
        - value: jpg
          label: jpg
      description: '随机封面后缀'
    card_random_cover_img_num:
      name: card_random_cover_img_num
      label: 卡片文章风格随机选择封面数量
      type: number
      default: 4
    auto_night_mode:
      name: auto_night_mode
      label: 暗夜模式总开关
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    night_mode:
      name: night_mode
      label: 暗夜模式顶部按钮(需要先打开暗黑模式总开关)
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    night_mode_start_time:
      name: night_mode_start_time
      label: 暗夜模式开始时间
      type: text
      placeholder: '暗夜模式开始时间 默认18'
      description: '注意：24小时制的小时. 比如:18'
    night_mode_end_time:
      name: night_mode_end_time
      label: 暗夜模式结束时间
      type: text
      placeholder: '暗夜模式结束时间,  默认6'
      description: '注意：24小时制的小时. 比如:6'
    top_search:
      name: top_search
      label: 搜索
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_summary:
      name: post_summary
      label: 首页文章摘要
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    custom_scroller:
      name: custom_scroller
      label: 自定义滚动条
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    custom_scroller_color:
      name: custom_scroller_color
      label: 自定义滚动条颜色
      type: color
      default: '#2474b5'
      placeholder: '网站主题色'
    Icp:
      name: Icp
      label: 'ICP 备案号'
      type: text
      placeholder: '填入 ICP 备案号，没有则不填. '
    PublicSecurityRecord:
      name: PublicSecurityRecord
      label: '网安备案号'
      type: text
      placeholder: '填入网安备案号代码，没有则不填'
    QR_code_zfb:
      name: QR_code_zfb
      label: '支付宝二维码链接'
      type: attachment
      placeholder: '支付宝收款二维码链接，不填不显示'
    QR_code_wx:
      name: QR_code_wx
      label: '微信二维码链接'
      type: attachment
      placeholder: '微信收款二维码链接，不填不显示'
head_img:
  label: 网页首部图片
  items:
    archives_patternimg:
      name: archives_patternimg
      label: 归档页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    links_patternimg:
      name: links_patternimg
      label: 友情链接页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    tag_patternimg:
      name: tag_patternimg
      label: 标签页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    categories_patternimg:
      name: categories_patternimg
      label: 分类页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    journals_patternimg:
      name: journals_patternimg
      label: 日志下文章页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    photos_patternimg:
      name: photos_patternimg
      label: 相册页面头部装饰图
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
    links_placeholder:
      name: links_placeholder
      label: 友情链接默认用户头像
      type: attachment
      default: https://cdn.jsdelivr.net/gh/hshanx/static@v1.0.2/default-bg.jpeg
post:
  label: 文章页
  items:
    post_toc:
      name: post_toc
      label: 目录
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    post_nepre:
      name: post_nepre
      label: 下一篇
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    open_read_progress:
      name: open_read_progress
      label: 是否使用阅读进度条
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 显示
        - value: false
          label: 关闭
    progress_color:
      name: progress_color
      label: 阅读进度条颜色
      type: color
      default: '#2474b5'
      placeholder: '阅读进度条颜色'
    post_max_wdth:
      name: post_max_wdth
      label: 文章最大宽度
      type: text
      default: '800px'
      placeholder: '文章最大宽度, 比如: 800px'
    content_font_size:
      name: content_font_size
      label: 文章正文字体大小
      type: text
      default: '1.12rem'
      placeholder: '文章正文字体大小, 比如: 1.16rem 或 14px'
    content_line_height:
      name: content_line_height
      label: 文章正文高度
      type: text
      default: '2rem'
      placeholder: '文章正文高度, 比如: 2rem 或 14px'
    enabled_visual_height:
      name: enabled_visual_height
      label: 文章页开启全屏图片
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    social_share:
      name: social_share
      label: 开启文章分享
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 是
        - value: false
          label: 否
    share_disabeld:
      name: share_disabeld
      label: 分享禁用
      type: text
      default: 'google,twitter,facebook'
      placeholder: '文章分享禁用社交软件'
      description: '文章分享禁用社交软件,比如: google,twitter,facebook,weibo,qq,tencent,qzone,linkedin,wechat,douban,diandian'
    enabled_katex:
      name: enabled_katex
      label: Katex 渲染
      type: radio
      data-type: bool
      default: false
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    copyright_clean:
      name: copyright_clean
      label: 简洁版权信息
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
    highlight_extra_languages:
      name: highlight_extra_languages
      label: 文章代码高亮语言
      type: textarea
      description: "默认已经包含：<code>php,diff,java,css,bash,json,perl,swift,plaintext,ruby,yaml,sql,vbnet,ini,scss,less,cpp,typescript,csharp,rust,python,python-repl,objectivec,r,shell,makefile,go,xml,markdown,lua,javascript,php-template,kotlin,c</code><br>如果需要添加其他语言，请按照相同格式添加。"
    highlight_style:
      name: highlight_style
      label: 文章代码高亮主题
      type: select
      default: 'default.min.css'
      options:
        - value: 'a11y-dark.min.css'
          label: 'a11y-dark.min.css'
        - value: 'a11y-light.min.css'
          label: 'a11y-light.min.css'
        - value: 'agate.min.css'
          label: 'agate.min.css'
        - value: 'an-old-hope.min.css'
          label: 'an-old-hope.min.css'
        - value: 'androidstudio.min.css'
          label: 'androidstudio.min.css'
        - value: 'arduino-light.min.css'
          label: 'arduino-light.min.css'
        - value: 'arta.min.css'
          label: 'arta.min.css'
        - value: 'ascetic.min.css'
          label: 'ascetic.min.css'
        - value: 'atom-one-dark-reasonable.min.css'
          label: 'atom-one-dark-reasonable.min.css'
        - value: 'atom-one-dark.min.css'
          label: 'atom-one-dark.min.css'
        - value: 'atom-one-light.min.css'
          label: 'atom-one-light.min.css'
        - value: 'brown-paper.min.css'
          label: 'brown-paper.min.css'
        - value: 'codepen-embed.min.css'
          label: 'codepen-embed.min.css'
        - value: 'color-brewer.min.css'
          label: 'color-brewer.min.css'
        - value: 'dark.min.css'
          label: 'dark.min.css'
        - value: 'default.min.css'
          label: 'default.min.css'
        - value: 'devibeans.min.css'
          label: 'devibeans.min.css'
        - value: 'docco.min.css'
          label: 'docco.min.css'
        - value: 'far.min.css'
          label: 'far.min.css'
        - value: 'felipec.min.css'
          label: 'felipec.min.css'
        - value: 'foundation.min.css'
          label: 'foundation.min.css'
        - value: 'github-dark-dimmed.min.css'
          label: 'github-dark-dimmed.min.css'
        - value: 'github-dark.min.css'
          label: 'github-dark.min.css'
        - value: 'github.min.css'
          label: 'github.min.css'
        - value: 'gml.min.css'
          label: 'gml.min.css'
        - value: 'googlecode.min.css'
          label: 'googlecode.min.css'
        - value: 'gradient-dark.min.css'
          label: 'gradient-dark.min.css'
        - value: 'gradient-light.min.css'
          label: 'gradient-light.min.css'
        - value: 'grayscale.min.css'
          label: 'grayscale.min.css'
        - value: 'hybrid.min.css'
          label: 'hybrid.min.css'
        - value: 'idea.min.css'
          label: 'idea.min.css'
        - value: 'intellij-light.min.css'
          label: 'intellij-light.min.css'
        - value: 'ir-black.min.css'
          label: 'ir-black.min.css'
        - value: 'isbl-editor-dark.min.css'
          label: 'isbl-editor-dark.min.css'
        - value: 'isbl-editor-light.min.css'
          label: 'isbl-editor-light.min.css'
        - value: 'kimbie-dark.min.css'
          label: 'kimbie-dark.min.css'
        - value: 'kimbie-light.min.css'
          label: 'kimbie-light.min.css'
        - value: 'lightfair.min.css'
          label: 'lightfair.min.css'
        - value: 'lioshi.min.css'
          label: 'lioshi.min.css'
        - value: 'magula.min.css'
          label: 'magula.min.css'
        - value: 'mono-blue.min.css'
          label: 'mono-blue.min.css'
        - value: 'monokai-sublime.min.css'
          label: 'monokai-sublime.min.css'
        - value: 'monokai.min.css'
          label: 'monokai.min.css'
        - value: 'night-owl.min.css'
          label: 'night-owl.min.css'
        - value: 'nnfx-dark.min.css'
          label: 'nnfx-dark.min.css'
        - value: 'nnfx-light.min.css'
          label: 'nnfx-light.min.css'
        - value: 'nord.min.css'
          label: 'nord.min.css'
        - value: 'obsidian.min.css'
          label: 'obsidian.min.css'
        - value: 'paraiso-dark.min.css'
          label: 'paraiso-dark.min.css'
        - value: 'paraiso-light.min.css'
          label: 'paraiso-light.min.css'
        - value: 'pojoaque.min.css'
          label: 'pojoaque.min.css'
        - value: 'purebasic.min.css'
          label: 'purebasic.min.css'
        - value: 'qtcreator-dark.min.css'
          label: 'qtcreator-dark.min.css'
        - value: 'qtcreator-light.min.css'
          label: 'qtcreator-light.min.css'
        - value: 'rainbow.min.css'
          label: 'rainbow.min.css'
        - value: 'routeros.min.css'
          label: 'routeros.min.css'
        - value: 'school-book.min.css'
          label: 'school-book.min.css'
        - value: 'shades-of-purple.min.css'
          label: 'shades-of-purple.min.css'
        - value: 'srcery.min.css'
          label: 'srcery.min.css'
        - value: 'stackoverflow-dark.min.css'
          label: 'stackoverflow-dark.min.css'
        - value: 'stackoverflow-light.min.css'
          label: 'stackoverflow-light.min.css'
        - value: 'sunburst.min.css'
          label: 'sunburst.min.css'
        - value: 'tokyo-night-dark.min.css'
          label: 'tokyo-night-dark.min.css'
        - value: 'tokyo-night-light.min.css'
          label: 'tokyo-night-light.min.css'
        - value: 'tomorrow-night-blue.min.css'
          label: 'tomorrow-night-blue.min.css'
        - value: 'tomorrow-night-bright.min.css'
          label: 'tomorrow-night-bright.min.css'
        - value: 'vs.min.css'
          label: 'vs.min.css'
        - value: 'vs2015.min.css'
          label: 'vs2015.min.css'
        - value: 'xcode.min.css'
          label: 'xcode.min.css'
        - value: 'xt256.min.css'
          label: 'xt256.min.css'
custom:
  label: 自定义
  items:
    TimeStatistics:
      name: TimeStatistics
      label: '站点运行时间统计'
      type: text
      description: '填入起始时间，格式：月/日/年 时:分:秒，如08/20/2018 12:00:00'
title:
  label: 页面标题
  items:
    links_title:
      name: links_title
      label: 友链页面标题
      type: text
      default: 友链
    jounarls_title:
      name: jounarls_title
      label: 日志页面标题
      type: text
      default: 日志
    tags_title:
      name: tags_title
      label: 标签页面标题
      type: text
      default: 标签列表
    categories_title:
      name: categories_title
      label: 分类列表页面标题
      type: text
      default: 分类列表
    achieve_title:
      name: achieve_title
      label: 归档页面标题
      type: text
      default: 归档
    photos_title:
      name: photos_title
      label: 相册页面标题
      type: text
      default: 相册
social:
  label: 社交网络
  items:
    #    wechat:
    #      name: wechat
    #      label: 微信二维码
    #      type: attachment
    sina:
      name: sina
      label: 新浪微博
      type: text
      placeholder: '用于展示底部新浪微博社交信息'
      description: '新浪微博主页链接'
    telegram:
      name: telegram
      label: Telegram
      type: text
      placeholder: '用于展示底部 Telegram 社交信息'
      description: 'Telegram 用户名'
    twitter:
      name: twitter
      label: Twitter
      type: text
      placeholder: '用于展示底部 Twitter 社交信息'
      description: 'Twitter 主页链接'
    qq:
      name: qq
      label: 腾讯 QQ
      type: text
      placeholder: '用于展示底部 QQ 社交信息'
      description: 'QQ 号码'
    github:
      name: github
      label: Github
      type: text
      placeholder: '用于展示底部 Github 社交信息'
      description: 'GitHub 主页链接'
    zhihu:
      name: zhihu
      label: 知乎
      type: text
      placeholder: '用于展示底部知乎社交信息'
      description: '知乎主页链接'
    mail:
      name: mail
      label: 邮箱
      type: text
      placeholder: '用于展示底部邮箱社交信息'
      description: '邮箱地址'
    rss:
      name: rss
      label: 订阅按钮
      type: radio
      data-type: bool
      default: true
      options:
        - value: true
          label: 开启
        - value: false
          label: 关闭
other:
  label: 其他
  items:
    Aplayer:
      name: Aplayer
      label: Aplayer吸底播放器
      type: text
      placeholder: '网易云歌单id'
      description: '网易云歌单id, 比如: 60198. 暂时就只能这样子了, 后面再优化吧'